# CREATION


In [2]:
import numpy as np
y = np.array([1, 2, 3, 4, 5])
print(y)


[1 2 3 4 5]


In [3]:
l = [2, 3, 4, 5]
l = np.array(l)
print(type(l))

<class 'numpy.ndarray'>


# You Can Make various types of arrays based on their dimensions
ndim is used to check the dimension of an array

In [4]:
l = np.array([[1, 2, 3, 4] , [5, 6, 7, 8]]) # No of elements in both should be same else it throws an error
l = np.array(l)
print(type(l))
print(l.ndim)

<class 'numpy.ndarray'>
2


In [5]:
l = np.array([1, 2, 3, 4], ndmin=10) # this will create an numpy array with 10 dimensions
print(l)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


# Special Numpy Arrays

In [6]:
# All elements filled with 0
import numpy as np
ar_zero = np.zeros(4)
ar_zero_d = np.zeros((3, 4)) # this will create a 3d array with 4 zeros in each dimension
print(ar_zero)
print(ar_zero_d)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# All elements filled with 1
ar_one = np.ones((3, 4))
print (ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# Empty array
ar_empty = np.empty(4)
print(ar_empty)

[0. 0. 0. 0.]


In [9]:
# array with a range
ar_rn = np.arange(1, 8)
print(ar_rn)

[1 2 3 4 5 6 7]


In [10]:
# all diagonal elements filled with 1
ar_dia = np.eye(3, 5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [19]:
# Create an array with specific interval
ar_lin = np.linspace(0, 1, num= 5) # num gives the no. of elements in each episode
print(ar_lin)

[0.   0.25 0.5  0.75 1.  ]


# Create numpy array with random numbers

In [12]:
# Using rand
ar_rand = np.random.rand(5) # This will create array with random values between 0 to 1
ar_rand1 = np.random.rand(2, 5) # this will create 2d array with random values between 0 to 1
print(ar_rand1)

[[0.98449901 0.33048574 0.93442626 0.49802707 0.86616404]
 [0.8522109  0.96365055 0.92418494 0.1898177  0.09830507]]


In [13]:
# Using randn
ar_randn = np.random.randn(4) # This will create an array of random values ranging from -1 to 1
ar_randn1 = np.random.randn(2, 4) # For 2D
print(ar_randn1)

[[-0.87187597  0.98858437  0.85661812  0.24808468]
 [-0.53848427  0.06951617 -1.09032927 -0.0844306 ]]


In [14]:
# Using ranf
ar_ranf = np.random.ranf(4) # This creates a random array with values ranging from 0.0 to 0.99 we can also define range as [0.0, 1.0)
ar_ranf1 = np.random.ranf((2, 4)) # For 2D
print(ar_ranf1) 

[[0.56454779 0.14017056 0.17058803 0.00352931]
 [0.25295623 0.06360279 0.22679573 0.18789592]]


In [15]:
# using randint
ar_randint = np.random.randint(1, 5, 3); # This will create a array of 3 elements and its range would be 1 to 5 
ar_randint1 = np.random.randint(1, 20, (2, 4)); # To Create 2D array
print(ar_randint1)

[[16 19  4 12]
 [10  4 12 14]]
