# Numpy Functions

In [6]:
import numpy as np
import timeit

var = np.array([1,2,3,4,6])


# Search

In [4]:
np.where(var < 3, 4, -3) # (condition, if true, if false)
np.where(var == 3) # get index


(array([2], dtype=int64),)

In [23]:
# Search sort - it returns the index where the element should be inserted to keep the array sorted by using binary search
x = np.searchsorted(var, 1, side='right') # it returns the index where should the element should be inserted  side is by default Left but if you want to search from end then give right
x1 = np.searchsorted(var, [1, 3, 5]) # it will return where should 1, 3 and 5 should be placed 
x1

array([0, 2, 4], dtype=int64)

# Sort

In [25]:
var1 = np.array([1, 3, 2, 7, 5, 4, 6])
print(np.sort(var1))

[1 2 3 4 5 6 7] <class 'reversed'>


# Filter

In [26]:
# copy data from a array to a new array
filtered_index = [True, False, True, False, True, False, True]
filteredArray = var1[filtered_index] # This will fill filtered array with the value in var1 at True 
filteredArray

array([1, 2, 5, 6])

# Shuffle

In [8]:
# shuffle - change indices of an given array randomly
np.random.shuffle(var)
print(var)



[2 3 6 4 1]


# unique

In [11]:
# it is used to get a unique data in a repeated array
varx = np.array([1,3, 42, 1, 1, 1, 2, 3, 3, 3, 2, 2, 2])
# uni = np.unique(varx, return_index=True) # this will give the index of first occurence
uni = np.unique(varx, return_counts=True) # This will return the no of occurences of the elements in the array
uni

(array([ 1,  2,  3, 42]), array([4, 4, 4, 1], dtype=int64))

# Resize

In [14]:
var_re = np.array([[1,2,3, 4, 5], [6, 7, 8, 9, 10]])
y = np.resize(var_re, (4, 2)) # This will reshape the array into desired shape first is no of row and second is no. of columns
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Flatten

It happens in different orders
1. 'C' means to flatten in row-major (C-style) order, It is the default type
2. 'F' means to flatten in column-major (Fortran-style) order
3. 'A' means to flatten in column-major order if 'a' is Fortran *contingous* in memory, row-major order otherwise
4. 'K' means to flatten 'a' in the order the elements occur in memory.


In [28]:
# It converts 2D array into 1D
print(y.flatten(order='F'))

[1 3 5 7 2 4 6 8]


# Ravel

In [31]:
print(np.ravel(y, order="F")) # same as flatten

[1 3 5 7 2 4 6 8]
