# Insert

In [16]:
import numpy as np
var = np.array([1, 2, 3, 4])
print(var)

[1 2 3 4]


In [17]:
var = np.insert(var, 4, 5) # (array, index ,value)
var = np.insert(var, (1, 3), 4) # insert at different indices at once
print(var)


[1 4 2 3 4 4 5]


In [5]:
# For 2D
var2 = np.array([[1, 2, 3], [4, 5, 6]])
var2 = np.insert(var2, 2, [7, 8, 9], axis=0) # You have to provide the axis
print(var2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Append
v = np.append(var2, [[10, 11, 12]], axis=0)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Delete

In [25]:
# var = np.delete(var, 0)
var = np.delete(var, np.where(var == 4))
print(var)

[1 2 3 5]
