# Joining
Means putting contents of two or more arrays in a single array

In [22]:
import numpy as np
var = np.array([1, 2, 3, 4])
var1 = np.array([5, 6, 7, 8])
ar = np.concatenate((var, var1)) # This will merge the two arrays
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
# For 2D 
var2 = np.array([[1, 2, 3, 4], [5, 6, 7 , 8]])
var3 = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
# Here we can concatenate wrt to their axis
# ar2D = np.concatenate((var2, var3)) # this will create a 2d array with all elements
ar2D = np.concatenate((var2, var3), axis=1)

ar2D

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [21]:
# Using Stack Function
vr = np.array([1, 2, 3,4])
vr1 = np.array([5, 6, 7, 8])
# ar_Stack = np.stack((vr, vr1), axis=1) # it will merge according to colums and you can use it on a 1D array also not like concatenate 
# ar_stack_hori = np.hstack((vr, vr1)) # this will merge according to rows
# ar_stack_vertical = np.vstack((vr, vr1)) # This will merge according to colums
ar_stack_height = np.dstack((vr, vr1)) # this will merge according to the height
# ar_Stack
# ar_stack_hori
# ar_stack_vertical
ar_stack_height

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

# Splitting
It breaks One array into multiple arrays

In [25]:
vars = np.array([1, 2, 3, 4, 5, 6])
ars = np.array_split(vars, 3) # This will split array in 3 parts and return a list
print(ars)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
# For 2D
vars1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
# ars1 = np.array_split(vars1, 2) 
# ars1 = np.array_split(vars1, 2, axis=1) # Split according to axis
# ars1 = np.hsplit(vars1, 2) # Same like splitting with axis 1
ars1 = np.vsplit(vars1, 2) # Same like splitting with axis 0
# ars1 = np.dsplit(vars1, 2) # It only works on array of 3 or more dimensions

ars1

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]