# Matrix

In [12]:
import numpy as np
varm = np.matrix([[1, 2], [4, 5]])
varm1 = np.matrix([[1, 2], [4, 5]])
print(varm)
var = np.array([[1,2,3], [4, 5, 6]])
var1 = np.array([[1,2,3], [4, 5, 6]])


[[1 2]
 [4 5]]


## Arithmetic Operations

In [7]:
# Additon and subtraction will be same
print(np.add(var, var1))
print(np.add(varm, varm1))

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]


In [15]:
# Multiplication - matrix have both dot(.) multiplication and cross(x) multiplication
print(var*var1)
print(varm.dot(varm1))

[[ 1  4  9]
 [16 25 36]]
[[ 9 12]
 [24 33]]


# Functions

In [16]:
# Transpose - colums becomes rows and rows become columns
print(varm.T) # this will change the matrix into its transpose

[[1 4]
 [2 5]]


In [17]:
# Swapaxes - it also changes rows to columns and colums to rows but for a specific axis
print(np.swapaxes(varm, 0, 1)) # It will convert 0 axis to 1


[[1 4]
 [2 5]]


In [18]:
# Inverse - A^-1 
print(varm)
print(np.linalg.inv(varm))

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [20]:
# Power - A^2 = AA it is performed by dot product
print(varm)
print(np.linalg.matrix_power(varm, 0)) # This will give the dot product of matrix with identity matrix
print(np.linalg.matrix_power(varm, 2)) # This will give the dot product of matrix with the power of the matrix,if n > 0
print(np.linalg.matrix_power(varm, -2)) # This will give the dot product of matrix with the inverse power of the matrix,if n < 0

[[1 2]
 [4 5]]
[[1 0]
 [0 1]]
[[ 9 12]
 [24 33]]
[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


In [22]:
# Determinant
print(varm)
print(np.linalg.det(varm))


[[1 2]
 [4 5]]
2.9999999999999996


In [23]:
# Rank
print(varm)
print(np.linalg.matrix_rank(varm))

[[1 2]
 [4 5]]
2


In [28]:
# EigenValues and EigenVectors
print(varm)
print(np.linalg.eigh(varm))

[[1 2]
 [4 5]]
EighResult(eigenvalues=array([-1.47213595,  7.47213595]), eigenvectors=matrix([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))


In [29]:
# Multiple dot product
print(np.linalg.multi_dot(varm1))

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)