# Numpy turtorial

In [83]:
import numpy as np

In [84]:
myarr = np.array([[3, 6, 3277788, 7]], np.int64)

In [85]:
myarr[0, 1]

6

In [86]:
myarr

array([[      3,       6, 3277788,       7]], dtype=int64)

In [87]:
myarr.shape

(1, 4)

In [88]:
myarr.dtype

dtype('int64')

In [89]:
  myarr[0, 1] = 45
    

In [90]:
myarr


array([[      3,      45, 3277788,       7]], dtype=int64)

# Array Creation : Conversion from other python structures


In [91]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [92]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [93]:
listarray.dtype

dtype('int32')

In [94]:
listarray.shape

(3, 3)

In [95]:
listarray.size

9

In [96]:
np.array({34, 23, 23})

array({34, 23}, dtype=object)

In [97]:
zeros = np.zeros((2, 5))

In [98]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
zeros.dtype

dtype('float64')

In [100]:
zeros.shape

(2, 5)

In [101]:
rng = np.arange(15)

In [102]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
lspace = np.linspace(1, 5, 4)

In [104]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [105]:
emp = np.empty((4,6))

In [106]:
emp


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22519779e-307, 2.11387449e-307, 1.89145198e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.02360935e-306, 1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        9.45699680e-308, 1.11258854e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306, 7.56599128e-307, 7.23168527e-308]])

In [107]:
emplike = np.empty_like(lspace)

In [108]:
emplike


array([1.        , 2.33333333, 3.66666667, 5.        ])

In [109]:
ide = np.identity(45)

In [110]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [111]:
ide.shape

(45, 45)

In [112]:
arr = np.arange(99)

In [113]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [114]:
arr = arr.reshape(3, 33)

In [115]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [116]:
arr = arr.ravel()

In [117]:
arr.shape

(99,)

In [118]:
x = [[1,2,3], [4,5,6], [7,1,0]]


In [119]:
ar = np.array(x)

In [120]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [121]:
ar.sum(axis=0)

array([12,  8,  9])

In [122]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [123]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [124]:
ar.flat

In [125]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [126]:
ar.ndim

2

In [127]:
ar.size

9

In [128]:
ar.nbytes

36

In [129]:
one = np.array([1, 2, 3, 4, 6, 7])

In [130]:
one.argmax()

5

In [131]:
one.argmin()

0

In [132]:
one.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [133]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [134]:
ar.argmin()

8

In [135]:
ar.argmax()

6

In [136]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [137]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [138]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [139]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [140]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [141]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [142]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [143]:
ar2 = np.array([[1, 2, 3],
       [2, 1, 3],
       [1, 6, 3]])

In [144]:
ar + ar2

array([[2, 4, 6],
       [6, 6, 9],
       [8, 7, 3]])

In [145]:
ar*ar2

array([[ 1,  4,  9],
       [ 8,  5, 18],
       [ 7,  6,  0]])

In [146]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [147]:
ar.sum()

29

In [148]:
ar.max()

7

In [149]:
ar.min()

0

In [150]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [151]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [152]:
type(np.where(ar>4))

tuple

In [153]:
np.count_nonzero(ar)

8

In [154]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [155]:
ar[1, 2] = 0

In [156]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [157]:
import sys

In [158]:
pyar = [0, 4, 55]


In [159]:
npar = np.array(pyar)

In [160]:
sys.getsizeof(1) * len(pyar)

84

In [161]:
npar.itemsize* npar.size

12

In [162]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [163]:
np.where(ar==6)

(array([], dtype=int64), array([], dtype=int64))

In [165]:
# ar.where(6)

In [166]:
# for i in ar:
#     if i == 5:
#         print(y)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [167]:
np.where(ar==5)

(array([1], dtype=int64), array([1], dtype=int64))

In [168]:
ar


array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [169]:
np.where(ar==6)

(array([], dtype=int64), array([], dtype=int64))

In [171]:
ar.trace(axis1=0)

6

In [ ]:
np.size(ar, axis=1)

3

In [ ]:
ar.view()

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [ ]:
np.__version__
np.show_config()

openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', 

In [ ]:
print(is 0 in ar)

SyntaxError: invalid syntax (3006367753.py, line 1)

In [ ]:
np.shape(ar)

(3, 3)

In [ ]:
ar = np.zeros((3, 3))


In [ ]:
np.any(ar)

False