# Shaping numpy array


In [4]:
import numpy as np
var = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

print(var)
print()
print(var.shape) # this will print a tuple value with rows, column

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [6]:
var1 = np.array([1, 2, 3, 4], ndmin=4)
print(var1.shape) # this will give the no of rows then after column

(1, 1, 1, 4)


# Reshaping array

In [22]:
var2 = np.array([1, 2, 3, 4, 5])
x = var2.reshape(1,1,1,1, 5) # this will create 5D array with 4 rows  
print(x)
print()
x = x.reshape(-1) # This will create a make the array 1D
print(x)

[[[[[1 2 3 4 5]]]]]

[1 2 3 4 5]
